_G.NPCCache = {}
_G.BlockCache = {}
_G.EffectCache = {}
_G.BGOCache = {}
_G.PlayerCache = {}
_G.SectionCache = {}

_G.NPC_MAX_ID = 1000
_G.BLOCK_MAX_ID = 1000
_G.EFFECT_MAX_ID = 1000
_G.BGO_MAX_ID = 1000
_G.PLAYER_MAX_CHARACTERS = 7

_G.SECTION_MAX_ID = 200

_G.NPC_MAX_AMOUNT = 8000
_G.BLOCK_MAX_AMOUNT = 50000
_G.EFFECT_MAX_AMOUNT = 2000
_G.BGO_MAX_AMOUNT = 8000
_G.PLAYER_MAX_AMOUNT = 200

_G.NPC = require 'engine/npc_t'
